jobs:
  include:
  - language: java
    jdk: openjdk8
    cache:
      directories:
      - "$HOME/.m2"
    before_install: cd backend
    install: true
    script: mvn -B test
deploy:
  provider: heroku
  api_key:
    secure: si0+A048Rml01+HfVhLIfTHjm+oxYQ5VCkKGlR78+Vfrgo904aPKvlOKQcgVqoQCtWsXQpabAGSaxjouOsDfez6ATjrOAmX51siRL2Oh5WL5U8PX7R7HMFRVXEbvsSnbQXvKhPlD3/MQZ0nzWODQAJUb+xRIXgeAX1eQxWDPlEagjv+p+ZdAswbFFK9vUmTm+lSt21dAvHHBdhHkFEuruFFHPZsYWjMnhQkLjhLhmmUJfCBfyuV5/fxbAyVYAlpNGj0PVGPUCsDPC7Xs9wq3F5XbpxS0OrCIUdNo+x+4fxVDt7d3m33YyeK/ebVb6IzsQf9JzoI5ZwzdrbvFuqqSqs8gCxYqnUL9OD0xVNS+9wE1fNxsQzuBN+AwbSfvKnm+/WrLA0PBVTltwI6jb7R9EAKS8gh5IEO8z20DFHtEHiDKSxE1lrkF3O0ssITzGtYdqGBtJ2Rm2xH1uNvxtxjIxwPjZ0BpTYz6K3gpKM+av2DsCQ73uRsamdxYFylF2cXZLvGpEKuC0wZ1WZmdQUTF/RvwsMn53KkIG6/YKgr+0jcsh0pSaqPRd8UPJMBud0/Bu/AvoK/4+d2PGgE6d/rZIWfkOxEpBbco5j3kB+Mak6YkszFQVR0y9oBm3OJt+167sfppsYsWLJMdhD1Pax3mbQwTS8OaUjP3MtRBsNbX00M=
  app: reservationtracker
  on: main
    repo: Don3y/table-reservation
  skip_cleanup: 'true'
