jobs:
  include:

  - language: java
    jdk: openjdk8
    cache:
      directories:
        - $HOME/.m2

    before_install: cd backend
    install: true

    script: mvn -B test  # mvn clean install is működne

    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: " gYOkXx2Wd/Vj2zxmSHlDnSB71pE0uph3wBMJ31ebM+VofO82Klca53cbq7KejyU959yAFpHCYqj9uJ5tHCZ/sBC9/HZcrFZuREey0WqQR/3j/ETUmIB/4r3Ldwhtf/kv6AMQkHMEqhT5LnC2U9WvuxCUnOA2YnqWprmAg5wwdXPwjwxTDnGb2Klvzcnhy6AC30W/kjtNmpTe9/R5MsN+WIB6K3M0YQ2cqwNd4Z8Pqd1A1DE0Wv3umni1L+UnJXLXpLewT162SoXOuKCpXTW9FFOn56kqgXx0AqZ27sOWkicq1S264fIHlD+OKDbAXKRsrYfMuc+JBZoBlILJWUwW9cfI6C95g/Mst0Xk7741WmU1qK9rsHsHt4TD8AGqTPTOMoL8BcKf4VFBcKanBOqDyWvPcf3dupnLU+dtSbfziq8Iaroir4cvzgGqZl29W2xPhHhix3r60i/fvYd+LRrbd+GK9vwEyGJR5sXrBHlvyanhjISyXHKcTZ5EMcX/O4z4hIIbthqYpn3GxHwlVqo+BRiqrnfjwNZpg6dufvH0YQAAerjw7YvBRfCOpI55WoRzHOZgxxlY4h5Se0ulfyHkv3MLzBxrO5DkdSca6Jx/weKIDoVnK1k0MbUTFJ4EsrjLL8TFfz7G4fhm9fVSz24XxLYU4Bpk+CAJNUojgejVHGI="
        app: reservationtracker
      on: main
