jobs:
  include:

  - language: java
    jdk: openjdk8
    cache:
      directories:
        - $HOME/.m2

    before_install: cd backend
    install: true

    script: mvn -B test  # mvn clean install is működne

    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "X72Vq5XPDdG07nzWTTJYeTHS2CWkIXo7RiwUGe+dfULm8j1988swxdKPrsgQbcRLpyoe5c4pBG1jL7pXilxL4hY3RqS1+0UqgegWUBamTG+hNdFofVbuV/IjHrIH+lptw26TwMxqJQZmMZLRwChz/uMPnuKc25HpZ0nuC/e4R/5he5xmVRZNPs9UxAFfpMr4TFKDVAT9AHZnGL5WfbK4Y81WpWTUgPnnUmD5+4buo3Sbdc6BwIxts5NQ2U7P0jvtIdzCNxdbiNhb75NF0PoHZT62BPHaSh0PwnSaqPO8uCOhwx6iPiEWVpkKuJL1G2KOJVsxm6QQ3Vqe9mMlqjFwRqHYtBu755F0dplF38yRWIua68iwCb65VPf11LD0sqThsNvj0ZKv2TRH8VPI3rnAm3jGdWeKNbUfviDpq4bF6gYO8OKcv963sNU6MZQ3PZ9qolNWNJn2WsV/0UsWBNjDagyw1tUOr5nZvGlFtV66P2VmQPNm3Bug7S0jyTIsjXsIjyPzpC9jevZWLR5zaBuO4nwtek51SdAmhCWqtnPeWxfxJTwnkKipayGs6CzgZM6QU9a6JbcSmmzGJzHJYZ82tKnRBe/r/ZZUUaVXiFZrDtdURqIuL90EFR23Rk8n0jtg+cTIAeAO3gDauUkdrcXxeaxoibjONDg/ns21yKfJEDs="
        app: reservationtracker
      on: main
